import serverAuth from '@/libs/serverAuth';
import { NextApiRequest, NextApiResponse } from 'next';
import prisma from '@/libs/prismadb';

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  //   if (req.method !== 'GET') {
  //     return res.status(405).end();
  //   }

  try {
    // const airport = await prisma.airport.findMany({});
    // console.log(airport);

    // [
    //   { code: 'AMS', name: '암스테르담' },
    //   { code: 'KTM', name: '카트만두' },
    //   { code: 'OSL', name: '오슬로' },
    //   { code: 'NOU', name: '누메아' },
    //   { code: 'AKL', name: '오클랜드' },
    //   { code: 'KHH', name: '가오슝' },
    //   { code: 'TPE', name: '타이페이' },
    //   { code: 'CPH', name: '코펜하겐' },
    //   { code: 'MUC', name: '뮌헨' },
    //   { code: 'CGN', name: '쾰른' },
    //   { code: 'FRA', name: '프랑크푸르트' },
    //   { code: 'VTE', name: '비엔티안' },
    //   { code: 'OVB', name: '노보시비르스크' },
    //   { code: 'SVO', name: '모스크바' },
    //   { code: 'VVO', name: '블라디보스토크' },
    //   { code: 'UUS', name: '사할린' },
    //   { code: 'LED', name: '상트페테르부르크' },
    //   { code: 'YKS', name: '야쿠츠크' },
    //   { code: 'IKT', name: '이르쿠츠크' },
    //   { code: 'KHV', name: '하바로프스크' },
    //   { code: 'BEY', name: '베이루트' },
    //   { code: 'LUX', name: '룩셈부르크' },
    //   { code: 'BKI', name: '코타키나발루' },
    //   { code: 'KUL', name: '쿠알라룸푸르' },
    //   { code: 'PEN', name: '페낭' },
    //   { code: 'MLE', name: '말레' },
    //   { code: 'ULN', name: '울란바토르' },
    //   { code: 'GUM', name: '괌' },
    //   { code: 'JFK', name: '뉴욕' },
    //   { code: 'EWR', name: '뉴욕/뉴어크' },
    //   { code: 'DFW', name: '댈러스' },
    //   { code: 'DTW', name: '디트로이트' },
    //   { code: 'LAS', name: '라스베이거스' },
    //   { code: 'LAX', name: '로스앤젤레스' },
    //   { code: 'MIA', name: '마이애미' },
    //   { code: 'MEM', name: '멤피스' },
    //   { code: 'SPN', name: '사이판' },
    //   { code: 'SFO', name: '샌프란시스코' },
    //   { code: 'SEA', name: '시애틀' },
    //   { code: 'ORD', name: '시카고' },
    //   { code: 'ATL', name: '애틀랜타' },
    //   { code: 'ANC', name: '앵커리지' },
    //   { code: 'ILN', name: '에어본  에어파크' },
    //   { code: 'IAD', name: '워싱턴' },
    //   { code: 'IND', name: '인디애나폴리스' },
    //   { code: 'PHL', name: '필라델피아' },
    //   { code: 'HNL', name: '호놀룰루' },
    //   { code: 'HOU', name: '휴스턴' },
    //   { code: 'RGN', name: '양곤' },
    //   { code: 'BAH', name: '바레인' },
    //   { code: 'DAC', name: '다카' },
    //   { code: 'CCS', name: '마이케티아' },
    //   { code: 'DAD', name: '다낭' },
    //   { code: 'HAN', name: '하노이' },
    //   { code: 'SGN', name: '호찌민' },
    //   { code: 'BRU', name: '브뤼셀' },
    //   { code: 'SOF', name: '소피아' },
    //   { code: 'GRU', name: '상파울루' },
    //   { code: 'BWN', name: '반다르스리브가완' },
    //   { code: 'CMB', name: '콜롬보' },
    //   { code: 'GOT', name: '고테버그' },
    //   { code: 'STO', name: '스톡홀름' },
    //   { code: 'BSL', name: '바젤' },
    //   { code: 'ZRH', name: '취리히' },
    //   { code: 'MAD', name: '마드리드' },
    //   { code: 'BCN', name: '바르셀로나' },
    //   { code: 'SIN', name: '싱가포르' },
    //   { code: 'DXB', name: '두바이' },
    //   { code: 'AUH', name: '아부다비' },
    //   { code: 'BUE', name: '부에노스 아이레스' },
    //   { code: 'GYD', name: '바쿠' },
    //   { code: 'LHR', name: '런던/히드로' },
    //   { code: 'MEL', name: '멜버른' },
    //   { code: 'BNE', name: '브리즈번' },
    //   { code: 'SYD', name: '시드니' },
    //   { code: 'VIE', name: '비엔나' },
    //   { code: 'TAS', name: '타슈켄트' },
    //   { code: 'THR', name: '테헤란' },
    //   { code: 'TLV', name: '텔아비브' },
    //   { code: 'CAI', name: '카이로' },
    //   { code: 'FCO', name: '로마' },
    //   { code: 'MXP', name: '밀라노' },
    //   { code: 'DEL', name: '델리' },
    //   { code: 'BOM', name: '뭄바이' },
    //   { code: 'MAA', name: '첸나이' },
    //   { code: 'DPS', name: '덴파사르' },
    //   { code: 'CGK', name: '자카르타' },
    //   { code: 'KOJ', name: '가고시마' },
    //   { code: 'KMQ', name: '고마쓰' },
    //   { code: 'KMJ', name: '구마모토' },
    //   { code: 'KKJ', name: '기타큐슈' },
    //   { code: 'NGS', name: '나가사키' },
    //   { code: 'NGO', name: '나고야' },
    //   { code: 'KIJ', name: '니가타' },
    //   { code: 'TAK', name: '다카마쓰' },
    //   { code: 'TOY', name: '도야마' },
    //   { code: 'NRT', name: '도쿄/ 나리타' },
    //   { code: 'HND', name: '도쿄/ 하네다' },
    //   { code: 'MYJ', name: '마쓰야마' },
    //   { code: 'KMI', name: '미야자키' },
    //   { code: 'CTS', name: '삿포로' },
    //   { code: 'SDJ', name: '센다이' },
    //   { code: 'FSZ', name: '시즈오카' },
    //   { code: 'AKJ', name: '아사히카와' },
    //   { code: 'AOJ', name: '아오모리' },
    //   { code: 'OSA', name: '오사카' },
    //   { code: 'KIX', name: '오사카/ 간사이' },
    //   { code: 'OIT', name: '오이타' },
    //   { code: 'OKJ', name: '오카야마' },
    //   { code: 'OKA', name: '오키나와' },
    //   { code: 'YGJ', name: '요나고' },
    //   { code: 'HKD', name: '하코다테' },
    //   { code: 'FKS', name: '후쿠시마' },
    //   { code: 'FUK', name: '후쿠오카' },
    //   { code: 'HIJ', name: '히로시마' },
    //   { code: 'CAN', name: '광저우' },
    //   { code: 'KWL', name: '구이린(계림)' },
    //   { code: 'KWE', name: '구이양' },
    //   { code: 'NNG', name: '난닝' },
    //   { code: 'NKG', name: '난징' },
    //   { code: 'KHN', name: '난창' },
    //   { code: 'NGB', name: '닝보' },
    //   { code: 'DLC', name: '다롄' },
    //   { code: 'LJG', name: '리장' },
    //   { code: 'MFM', name: '마카오' },
    //   { code: 'MDG', name: '무단장' },
    //   { code: 'PEK', name: '베이징' },
    //   { code: 'PVG', name: '상하이/ 푸동' },
    //   { code: 'XMN', name: '샤먼' },
    //   { code: 'SIA', name: '서안' },
    //   { code: 'SHE', name: '선양' },
    //   { code: 'SZX', name: '선전' },
    //   { code: 'SJW', name: '스자좡' },
    //   { code: 'XIY', name: '시안' },
    //   { code: 'SYX', name: '싼야' },
    //   { code: 'YNJ', name: '옌지' },
    //   { code: 'YNZ', name: '옌청' },
    //   { code: 'YNT', name: '옌타이' },
    //   { code: 'URC', name: '우루무치' },
    //   { code: 'WEH', name: '웨이하이' },
    //   { code: 'CGO', name: '정저우' },
    //   { code: 'TNA', name: '지난' },
    //   { code: 'CSX', name: '창사' },
    //   { code: 'CGQ', name: '창춘' },
    //   { code: 'CTU', name: '청두' },
    //   { code: 'CKG', name: '충칭' },
    //   { code: 'TAO', name: '칭다오' },
    //   { code: 'KMG', name: '쿤밍' },
    //   { code: 'TSN', name: '톈진' },
    //   { code: 'HRB', name: '하얼빈' },
    //   { code: 'HAK', name: '하이커우' },
    //   { code: 'HGH', name: '항저우' },
    //   { code: 'HKG', name: '홍콩' },
    //   { code: 'HIA', name: '화이안' },
    //   { code: 'PRG', name: '프라하' },
    //   { code: 'STI', name: '산티아고' },
    //   { code: 'TSE', name: '아스타나' },
    //   { code: 'ALA', name: '알마티' },
    //   { code: 'DOH', name: '도하' },
    //   { code: 'REP', name: '시엠립' },
    //   { code: 'PNH', name: '프놈펜' },
    //   { code: 'YVR', name: '밴쿠버' },
    //   { code: 'YYC', name: '캘거리' },
    //   { code: 'YYZ', name: '토론토' },
    //   { code: 'KWI', name: '쿠웨이트' },
    //   { code: 'FRU', name: '비슈케크' },
    //   { code: 'BKK', name: '방콕' },
    //   { code: 'DMK', name: '방콕/돈므앙' },
    //   { code: 'CNX', name: '치앙마이' },
    //   { code: 'HKT', name: '푸껫' },
    //   { code: 'IST', name: '이스탄불' },
    //   { code: 'ASB', name: '아쉬가바트' },
    //   { code: 'ROR', name: '코로르' },
    //   { code: 'WAW', name: '바르샤바' },
    //   { code: 'CDG', name: '파리' },
    //   { code: 'NAN', name: '난디' },
    //   { code: 'HEL', name: '헬싱키' },
    //   { code: 'MNL', name: '마닐라' },
    //   { code: 'CEB', name: '세부' },
    //   { code: 'SFS', name: '수비크' },
    //   { code: 'KLO', name: '칼리보' },
    //   { code: 'CRK', name: '클라크필드' },
    //   { code: 'TAE', name: '대구' },
    //   { code: 'PUS', name: '부산' },
    //   { code: 'GMP', name: '서울/ 김포' },
    //   { code: 'CJU', name: '제주' },
    // ].map(async (res) => {
    //   await prisma.airport.create({
    //     data: {
    //       name: res.name,
    //       code: res.code,
    //     },
    //   });
    // });

    return res.status(200);
  } catch (error) {
    console.log(error);
    return res.status(400).end();
  }
}
